my_postgres_db: 
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: Bake59as
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: dbt
      
      
      connect_timeout: 10 # default 10 seconds
    
  